### ISSUE TITLE
Rename vpp-base to fpp-vpp

### ISSUE THREAD

**Issue by korroot** [travelping/fpp-vpp#14]
This repository should be renamed to `fpp-vpp`.

Also, after rename, we need to update application repositories to adjust the base image.

Maybe we should consider versioning of fpp-vpp as a standalone project, and external dependency should be described in release notes, for example fpp-vpp 22.02.1 will have VPP 22.02 as an external dependency. When upgrading the VPP version, follow the release version of VPP and add internal version in the last character like 22.02.2/22.02.3 if `fpp-vpp` is based on VPP 22.02 release. If VPP version is changed to 22.06, then `fpp-vpp` will get 22.06.1/22.06.2 etc

**Comment by Sina-Mara** [comment]
closed as fpp-vpp has been released and made public.
